# -*- coding: utf-8 -*-
{
    'name': 'EduLance',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'All-in-one education CRM for language schools and tutoring centers',
    'author': 'Databulance',
    'website': 'https://databulance.com',
    'support': 'support@databulance.com',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'portal', 'calendar', 'website', 'hr', 'account',
    ],
    'data': [
        'security/edu_lance_groups.xml',
        'security/ir.model.access.csv',
        'data/edu_sequence_data.xml',
        'data/edu_level_data.xml',
        'data/edu_subject_data.xml',
        'views/res_config_settings_views.xml',
        'views/edu_subject_views.xml',
        'views/edu_level_views.xml',
        'views/edu_pipeline_stage_views.xml',
        'views/edu_student_views.xml',
        'views/edu_teacher_views.xml',
        'views/edu_lead_views.xml',
        'views/edu_curriculum_views.xml',
        'views/edu_group_views.xml',
        'views/edu_session_views.xml',
        'views/edu_homework_views.xml',
        'views/edu_subscription_views.xml',
        'views/edu_resource_views.xml',
        'views/edu_payout_views.xml',
        'views/edu_menu_views.xml',
        'views/edu_portal_templates.xml',
        'wizard/edu_migration_wizard_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'edu_lance/static/src/css/portal.css',
            'edu_lance/static/src/js/portal.js',
        ],
    },
    'images': ['static/description/banner.png', 'static/description/icon.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
